#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 6.1
#  in conjunction with Tcl version 8.6
#    Jun 10, 2021 01:22:12 PM CEST  platform: Darwin

import sys
from tkinter import filedialog

from plot import PieLive as pl

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk

    py3 = False
except ImportError:
    import tkinter.ttk as ttk

    py3 = True


def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top


def openProject(p1):
    print('Welcome_view_support.openProject')
    root = tk.Tk()
    root.withdraw()

    file_path = filedialog.askopenfilename()
    plotLive()
    sys.stdout.flush()


def plotLive():
    pie_plotter = pl.PieLive()
    pie_plotter.filter_zero()
    pie_plotter.plot()


def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None


if __name__ == '__main__':
    import Welcome_view
    Welcome_view.vp_start_gui()
